- name: Sync issues
  id: sync
  uses: cobraz/todoist-action@v1
  with:
    github-token: ${{ secrets.GH_TOKEN }}
    todoist-token: ${{ secrets.TODOIST_TOKEN }}
    query:
      updated:>2020-06-01 archived:false sort:updated-desc assignee:fullcontent
      -label:backlog
    sync-file-name: ./sync.json
